name: book_deploy
 
# execute this workflow automatically when push to master
# + workflow_dispatch
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install -r jupyter_notebook/requirement.txt

    # Build the book
    - name: Build the book
      run: |
        cd jupyter_notebook
        jupyter-book build sudoku.ipynb
        cd ..

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./jupyter_notebook/_build/html

